import './globals.css'
import { ubuntu } from './_fonts'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${ubuntu.variable}`}>
      <body className='font-ubuntu bg-slate-200'>
        {children}
      </body>
    </html>
  )
}
